### ISSUE TITLE
Give restapi basic security

### ISSUE THREAD

**Issue by UO270115** [Arquisoft/radarin_en2b#106]
We were thinking about restapi security. If someone is able to connect to the database or even try to perform some different malicious restapi calls maybe the security is compromised. We thought about using authentication keys to validate and perform secure and trustworthy operations.

I am not very sure if it is worthy enough comparing to the amount of work it implies and the final delivery count down. If it is, do you know any great ibrary to perfom it?

Thanks in advance for the help.

**Comment by pglez82** [comment]
Some security in the resapi is necessary. We do not want to allow anyone to do petitions there without any auth system. 

There are lots of information about how to secure an express api. The simplest approach that I can think of could be this library: https://www.npmjs.com/package/express-basic-auth. Just store in the db a username and password for each user registered in your system and check those credentials in each api call.
