### ISSUE TITLE
5. Building Block View

### ISSUE THREAD

**Issue by UO270115** [Arquisoft/radarin_en2b#21]
5.1. Whitebox Overall System

5.2. Level 2

5.3. Level 3

**Comment by UO270803** [comment]
![WhatsApp Image 2021-02-20 at 11 54 44](https://user-images.githubusercontent.com/60621412/108593166-774e0580-7372-11eb-836a-b5e216a95d4b.jpeg)
At the moment it is looking like this. Level 2 will look in depth the Interface Layer and the Data Acces Layer, what do you think about it?

**Comment by UO270115** [comment]
I think it is well explained as a diagram. I understand that the depth of the explanation is increased as the levels raised but some parts (the ones outside the box) are repeated several times and I am not very sure if that is ok.

**Comment by UO270803** [comment]
We did that as the levels are actually the same diagram but in different depths, then the elements are the same and some appear to be repeated.
