### ISSUE TITLE
6. Runtime View

### ISSUE THREAD

**Issue by UO270115** [Arquisoft/radarin_en2b#22]
6.1. <Runtime Scenario 1>

6.2. <Runtime Scenario 2>

6.3. …​

6.4. <Runtime Scenario n>

**Comment by UO270115** [comment]
@pglez82 I have opened an issue that was already created, so this one is duplicated sorry. Could you delete it or something similar? I think the classmates cannot.

**Comment by pglez82** [comment]
I gave you admin permission over the repository. Try to delete it yourself now.
