### ISSUE TITLE
8. Cross-cutting Concepts

### ISSUE THREAD

**Issue by UO270115** [Arquisoft/radarin_en2b#23]
8.1. Domain model

8.2. <Concept 2>

8.3. <Concept n>

**Comment by UO270115** [comment]
Domain Model

![domainModel](https://user-images.githubusercontent.com/60620700/108404307-fc74d580-721f-11eb-8fb1-ddaeb5ceabe5.png)

**Comment by UO270803** [comment]
It is lookin good, I would not add anything else at the moment
