### ISSUE TITLE
11. Risks and Technical Debts

### ISSUE THREAD

**Issue by UO271405** [Arquisoft/radarin_en2b#28]
I have just finished point 11 of documentation. What do you think about it? Do you think of any technical risk I have missed? Is the priority ok?

---------------------

We will show a list of the technical risks or technical debts of the project, ordered by priority.

	-Lack of time: One of the problems we may have is that we do not have time enough for working on the project due to other subjects.
	-Lack of experience doing this type of projects: None of the members of the group are used to do this kind of projects starting from scratch. 
	-Understanding new applications: We have to learn about new applications and technologies because we have never used them before.

---------------

**Comment by UO270115** [comment]
For now, I think they are ok. Regarding priority, in my opinion the order is reversed.
