### ISSUE TITLE
Research about MongoDB

### ISSUE THREAD

**Issue by UO270115** [Arquisoft/radarin_en2b#43]
How to do mongo queries and schemas.

Also, how to incorporate a mongo db structure in a react project for example.

**Comment by ucusita** [comment]
Hi, can I help you with this issue?

**Comment by ucusita** [comment]
Hi @UO270115 may be I can add to your work.

**Comment by pglez82** [comment]
Hi @ucusita. Even if this repository is public, it is not accepting pull requests from external members. The repository is an assignment, part of course in the University of Oviedo, in which only the students should participate.

Sorry for the misunderstanding.

**Comment by UO270115** [comment]
Mongodb indexes too.
