### ISSUE TITLE
SOLID Authentication

### ISSUE THREAD

**Issue by uo269787** [Arquisoft/radarin_en2b#44]
Which methods / libraries to use to log in to a pod and grant an application access.

Tokens that may need to be stored and how.

**Comment by uo269787** [comment]
We have a client side web application that needs to consume resources from the backend and they should be authorized.

**Comment by uo269787** [comment]
We have a clientside webapp that needs to consume resource from the backend, and the client should be authorized.

I think we are in the same situation as in [this forum post](https://forum.solidproject.org/t/use-solid-pod-as-back-end-login/1440)

When I thought I finally understood the process a bit and how to apply it to our project the post was revived (a few minutes ago) and now I am even more confused.

I also have some doubts about the database, I assume it should be secured and not just open to the public, as it is dealing with location data. We could secure it using jsonwebtokens, giving already logged in users a JWT signed by us, which contains the user's webid and later validating it in the REST API request. I think this should be fine if we manage to confirm a user's identity in our server, preferably without requiring a second log in, and that's the problem.

**Comment by uo269787** [comment]
I could not get solid-node-client working under react-native, It was giving compile time type errors from one of its dependencies that is also used by many others without issue, I tried downgrading it but it still didn't work.

I also may be misunderstanding solid-node-client documentation but I don't think loging to ESS pods would be the best experience for users due to the needing token generation if we want to login to their pods and their quick expiration date.

I also tried solid-auth-fetcher at first with no success either.

I tried everything in expo, It might have affected my testing.

At this point we have decided to start just with the webapp in react so we can get an initial version ready were we can at least  show something working. 

@pglez82

**Comment by pglez82** [comment]
Good job. Definitively this is not an easy problem. I was testing the solid-node-client library in node.js and it works well. I created a basic example here (https://github.com/pglez82/solid_auth_example). The problem starts when trying to use the library in react native, and as you say, problem are the dependencies. React-native do not run a full node.js environment so the library 'fs' can not be used. I can see two alternatives but there may be others:

1. Try to make a version of solid-node-client library that runs in react-native. For that, one would have to start replacing the fs library with something like react-native-fs. This change shouldn't be too difficult but other problems may arise during the process. The obvious advantage of this approach is that others could make use of this 'new' library and you would be contributing to the project.
2. Access the pod from the restapi and not from the app. This way, the app talks with the server and the server with the pod. Obviously this in a change in the architecture.

**Comment by pglez82** [comment]
I thing that something that may be worth trying is to post the question in https://forum.solidproject.org/. Maybe someone can share some light there.

**Comment by pglez82** [comment]
@uo269787, is this issue still open? In the solid forum (https://forum.solidproject.org/t/login-in-solid-pods-with-react-native/4116/4), the creator of the library has offered his help to run it in react native.

**Comment by uo269787** [comment]
More resources for the authentication process: https://solid.github.io/authentication-panel/solid-oidc-primer/
Which I didn't come across while looking for information at first. 

I did find: https://solid.github.io/authentication-panel/solid-oidc , I should have checked the repo :/

Their link to "this version" is failing with 404 though: https://solid.github.io/specification/solid-oidc/, most likely because it was moved from specification to authentication-panel.

I am not sure why but when doing  GET https://uo269787.inrupt.net/profile/card#me in the XML solid:oidcIssuer doesn't appear. It is already reporteed in NSS

solid/node-solid-server issue 1510 is already open

**Comment by uo269787** [comment]
I got half of it working properly under react native :D
I have [this repo](https://github.com/uo269787/solid-react-native-tests) where I have recreated some tests that I did in the past with solid libraries and the new ones that I did today after reading the primer, the most important being the AppAuth one.

A bit of explanation:
[react-native-app-auth](https://github.com/FormidableLabs/react-native-app-auth) provides a very easy way to aquire the tokens securely in react native using a browser modal window and handling part of the redirection. It requires a compliant oidc provider.

This handles one of the steps in the auth flow and the one I think is the trickiest for native (spawning the browser / webview and redirecting). The little example that I have there uses dynamic client registration for the app. We could also provide our app a unique webId in the heroku webapi in the /webid#this endpoint, more info [here](https://solid.github.io/authentication-panel/solid-oidc-primer/#authorization-code-pkce-flow-step-6), I am not exactly sure on how to implement this though.

The second half of it would be using a solid-client to access data. I now have to look into solid-client-authn-node. Since we can get the idToken, a refreshToken and a Bearer authToken we should have enough.

I need to look a bit more into it but I think this are the ones that session.handleRedirect() fetches from the server after decoding the code from the url. (steps 11 - 21).

I thought about storing them in [react-native-keychain](https://github.com/oblador/react-native-keychain), which maybe could serve as a backend for IStorage from inrupt libraries in a possible solid-client-authn-react-native.

@pglez82

**Comment by uo269787** [comment]
Using the library react-native-app-auth is not really needed and I dont't think it's using DPoP tokens yet, unlike inrupt libraries. The problem is that I am not able to compile the example using WebView: SolidClientAuthnNodeBare, so I got a bit further not using it for everything.

I'm currently stuck in _stream_transform not being detected properly.

There is also the fix_pbkdf2 python script needed to fix wrong output of a single file deep in the dependency tree when it goes though rn_nodeify, which is very hacky but it's the solution that I found easier (much better than editing it manually every yarn install).

**Comment by uo269787** [comment]
Here is relevant snippet from inrupt libraries to create the fetch function needed for authenticated requests in their solid client:

https://github.com/inrupt/solid-client-authn-js/blob/40e67c4ce563da26b3c9677ac8eb831248c8f3b6/packages/browser/src/authenticatedFetch/fetchFactory.ts#L22-L48

We already have a bearer token, so hacking something together should be easy. Refreshing the token would require a bit of attention. I think the same package in the node version implements it, but there is also the refresh function that exists in [react-native-app-auth](https://github.com/FormidableLabs/react-native-app-auth) which should make things easier.

We are no longer going to do the mobile app, but I wanted to update with my latests findings.
