### ISSUE TITLE
Doubt about RestAPI and MongoDB

### ISSUE THREAD

**Issue by UO270115** [Arquisoft/radarin_en2b#58]
While doing the query to check who user's friends are near within a range, I realize that instead of using the whole User collection I only need and I must use the friend list obtained from the user's pod passed as parameter in the corresponding request (I suppose). Can I use that userList (subcollection from User) to perform the query as it is below?

// Find the user's friends that are near
```javascript
router.post("user/location/near", async (req, res) => {
    let userLocation = req.body.userLocation;
    let userFriends = req.body.friends; // subcollection of User
    let userNearByFriends = await userFriends.find({ location: {
                                                    $near: userLocation,
                                                    $minDistance: 10, // meters
                                                    $maxDistance: 100
                                                } 
                                            })
    res.send(userNearByFriends)
})
```

I have not tested it yet because I have checked the postman web application but I am not very sure how to use it in order to automatically generate several json objects as if they were users of friends (that what I have understood in the meeting when you give me the tip). @pglez82

**Comment by pglez82** [comment]
I have never used mongodb in any of my projects so, even the query looks good, you need to test it and check if it works.

What I am not sure about is how you receive the parameters. You are doing a post request, which seems fine, and then, you are receiving the parameters in the request body. What I would do, is passing the body as a json (with the location and the friends all together). You can check how to receive a json in the body [here](https://stackoverflow.com/questions/10005939/how-do-i-consume-the-json-post-data-in-an-express-application) and how to send a json in the body using postman [here](https://learning.postman.com/docs/sending-requests/requests/#raw-data).

PS. I have edited your issue to format the code. It is  easier to read.

**Comment by pglez82** [comment]
where you able to get it to work Andrea? I am curious if your approach was good.

Pablo

**Comment by UO270115** [comment]
Yes. I have been abled to make it work. I think my code is not the best approach with the best performance but is what I have now. I will do the pull request in some minutes.
